# Generated by Django 5.2.3 on 2025-07-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Doença')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Doença')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Sintoma')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Sintoma')),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_diagnostico', models.DateField(auto_now_add=True, verbose_name='Data do Diagnóstico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Diagnóstico')),
                ('arquivo_diagnostico', models.FileField(blank=True, null=True, upload_to='diagnosticos/', verbose_name='Anexar Arquivo')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doenca', verbose_name='Doença Diagnosticada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-data_diagnostico'],
            },
        ),
        migrations.AddField(
            model_name='doenca',
            name='sintomas_comuns',
            field=models.ManyToManyField(blank=True, to='app.sintoma', verbose_name='Sintomas Comuns'),
        ),
    ]
